# Hax 监控
HAX = true

# 天气预报
CITY = ["安徽", "芜湖市"]
#101220301

# 机场签到
# 邮箱，同时支持普通用户名
# 密码
# 链接，只支持 SSPanel 类型。删除 /auth/login
[[AIRPORT]]
email = "omg19@qq.com"
password = "qwer1234"
url = "https://zhuzhu12.com"

[[AIRPORT]]
email = "grazia.uug.j.n5.2@gmail.com"
password = "qqqq1111"
url = "https://zhuzhu12.com"

[[WPS]]
cookie = "appcdn=qn.cache.wpscdn.com;wpsua=V1BTVUEvMS4wICh3ZWIta2RvY3M6Q2hyb21lXzExMC4wLjAuMDsgd2luZG93czpXaW5kb3dzIDEwLjA7IEMtZDRlRURCVDJXWnVvZkJxdzRhMVE9PTpRMmh5YjIxbElDQXhNVEF1TUM0d0xqQT0pIENocm9tZS8xMTAuMC4wLjA=; csrf=5Qc4FZJTFCYxkST4CDKcrkxdJxEFh76f;wps_sid=V02SZ_DZ0RI0AnrTE69zNyA6Xqg3buk00aaf7337000117199a;"

# GLaDOS【WEB】
# https://glados.network cookie
[[GLADOS]]
cookie = "_ga=GA1.2.258717642.1676707224; _gid=GA1.2.545612190.1676707235;koa:sess=eyJ1c2VySWQiOjI3MTQ4NSwiX2V4cGlyZSI6MTcwMTcwOTcyMjQ3NCwiX21heEFnZSI6MjU5MjAwMDAwMDB9; koa:sess.sig=ovyojV-VbqyU4quMab3f4dQajmk;"

[[CLOUD189]]
password = "tyyp2022.Q"
phone = "19855326910"